name: Open Issues alerts

on:
  schedule:
    - cron: '0 0 * * *' # Every 24 hours

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Create alerts
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
        working-directory: scripts
        run: ./openIssuesAlert.sh
